apiVersion: v1
kind: Namespace
metadata:
  name: wiki-mechanicum
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: wiki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wiki
    app.kubernetes.io/version: "2"
    helm.sh/chart: wiki-3.0.0
  name: wiki
  namespace: wiki-mechanicum
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: wiki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wiki
    app.kubernetes.io/version: "2"
    helm.sh/chart: wiki-3.0.0
  name: wiki
  namespace: wiki-mechanicum
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: wiki
    app.kubernetes.io/name: wiki
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: wiki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wiki
    app.kubernetes.io/version: "2"
    helm.sh/chart: wiki-3.0.0
  name: wiki
  namespace: wiki-mechanicum
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: wiki
      app.kubernetes.io/name: wiki
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/instance: wiki
        app.kubernetes.io/name: wiki
    spec:
      containers:
      - env:
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: cnpg-wiki-mechanicum-rw
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: wiki
        - name: DB_USER
          value: wiki
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: cnpg-wiki-mechanicum-app-user
        - name: DB_SSL
          value: "false"
        - name: DB_SSL_CA
          value: ""
        - name: HA_ACTIVE
          value: "false"
        image: requarks/wiki:2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: wiki
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources: {}
        securityContext: {}
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
      securityContext: {}
      serviceAccountName: wiki
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cnpg-wiki-mechanicum-backups
  namespace: wiki-mechanicum
spec:
  configuration:
    destinationPath: s3://wiki-mechanicum-backups/
    endpointURL: http://garage.irminsul:3900
    s3Credentials:
      accessKeyId:
        key: ACCESS_KEY_ID
        name: s3-backup-credentials
      region:
        key: REGION
        name: s3-backup-credentials
      secretAccessKey:
        key: ACCESS_SECRET_KEY
        name: s3-backup-credentials
  retentionPolicy: 30d
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-wiki-mechanicum-app-user
  namespace: wiki-mechanicum
spec:
  data:
  - remoteRef:
      key: kv/nekropolis/wiki-mechanicum/postgres-app-user
      property: username
    secretKey: username
  - remoteRef:
      key: kv/nekropolis/wiki-mechanicum/postgres-app-user
      property: password
    secretKey: password
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: cnpg-wiki-mechanicum-app-user
    template:
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-wiki-mechanicum-superuser
  namespace: wiki-mechanicum
spec:
  data:
  - remoteRef:
      key: kv/nekropolis/wiki-mechanicum/postgres-superuser
      property: username
    secretKey: username
  - remoteRef:
      key: kv/nekropolis/wiki-mechanicum/postgres-superuser
      property: password
    secretKey: password
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: cnpg-wiki-mechanicum-superuser
    template:
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-credentials
  namespace: wiki-mechanicum
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/nekropolis/wiki-mechanicum/s3-backup-credentials
      metadataPolicy: None
      property: ACCESS_KEY_ID
    secretKey: ACCESS_KEY_ID
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/nekropolis/wiki-mechanicum/s3-backup-credentials
      metadataPolicy: None
      property: ACCESS_SECRET_KEY
    secretKey: ACCESS_SECRET_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: kv/nekropolis/wiki-mechanicum/s3-backup-credentials
      metadataPolicy: None
      property: REGION
    secretKey: REGION
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: s3-backup-credentials
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    kube-vip.io/loadbalancerIPs: 192.168.13.13
  name: wiki-js
  namespace: wiki-mechanicum
spec:
  ingressClassName: cilium
  rules:
  - host: mechanicum.nekropolis.irminsul
    http:
      paths:
      - backend:
          service:
            name: wiki
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: mechanicum.irminsul
    http:
      paths:
      - backend:
          service:
            name: wiki
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mechanicum.irminsul
    - mechanicum.nekropolis.irminsul
    secretName: wiki-certificate
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-wiki-mechanicum
  namespace: wiki-mechanicum
spec:
  backup:
    target: prefer-standby
  bootstrap:
    initdb:
      database: wiki
      owner: wiki
      secret:
        name: cnpg-wiki-mechanicum-app-user
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 18
    name: postgresql-standard-trixie
  instances: 3
  plugins:
  - isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: cnpg-wiki-mechanicum-backups
  storage:
    size: 10Gi
  superuserSecret:
    name: cnpg-wiki-mechanicum-superuser
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-cnpg-wiki-mechanicum
  namespace: wiki-mechanicum
spec:
  backupOwnerReference: self
  cluster:
    name: cnpg-wiki-mechanicum
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: 0 0 23 * * THU
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app.kubernetes.io/instance: wiki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wiki
    app.kubernetes.io/version: "2"
    helm.sh/chart: wiki-3.0.0
  name: wiki-test-connection
  namespace: wiki-mechanicum
spec:
  containers:
  - args:
    - wiki:80
    command:
    - wget
    image: busybox
    name: wget
  restartPolicy: Never
