apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-credentials
spec:
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: kv/nekropolis/wiki-mechanicum/s3-backup-credentials
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: kv/nekropolis/wiki-mechanicum/s3-backup-credentials
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
        property: ACCESS_SECRET_KEY
    - secretKey: REGION
      remoteRef:
        key: kv/nekropolis/wiki-mechanicum/s3-backup-credentials
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
        property: REGION
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: s3-backup-credentials
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-wiki-mechanicum-superuser
spec:
  data:
    - secretKey: username
      remoteRef:
        key: kv/nekropolis/wiki-mechanicum/postgres-superuser
        property: username
    - secretKey: password
      remoteRef:
        key: kv/nekropolis/wiki-mechanicum/postgres-superuser
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: cnpg-wiki-mechanicum-superuser
    template:
      type: kubernetes.io/basic-auth
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-wiki-mechanicum-app-user
spec:
  data:
    - secretKey: username
      remoteRef:
        key: kv/nekropolis/wiki-mechanicum/postgres-app-user
        property: username
    - secretKey: password
      remoteRef:
        key: kv/nekropolis/wiki-mechanicum/postgres-app-user
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: cnpg-wiki-mechanicum-app-user
    template:
      type: kubernetes.io/basic-auth
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
