apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-credentials
spec:
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: kv/nekropolis/trilium/s3-backup-credentials
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: kv/nekropolis/trilium/s3-backup-credentials
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
        property: ACCESS_SECRET_KEY
    - secretKey: REGION
      remoteRef:
        key: kv/nekropolis/trilium/s3-backup-credentials
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
        property: REGION
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: s3-backup-credentials
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s
