apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs-2026
  volumeMode: Filesystem

