# https://github.com/TriliumNext/helm-charts/blob/main/charts/trilium/values.yaml

controllers:
  main:
    containers:
      trilium:
        image:
          repository: triliumnext/notes
          tag: v0.92.4
          pullPolicy: IfNotPresent
        env:
          TRILIUM_DATA_DIR: /home/node/trilium-data

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: trilium-data

configuring:
  general:
    instanceName: "trilium"
    noAuthentication: false
    noBackup: false
  network:
    host: "0.0.0.0"
    port: 8080
    https: false
    trustedReverseProxy: true

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: false
